### ISSUE TITLE
Crash when picking up lava in bucket or place water on an existing water source

### ISSUE THREAD

**Issue by shortybsd** [TechReborn/RebornCore#15] opened 2016-04-13 02:28 UTC
The problem persists if you have 2 buckets in inventory and you pick up one bucket. The second bucket will crash your client every time. Problem is in the if check, it doesn't check the state of the lava, if you right click with a bucket on a flowing, non lava source is when it crashes. The same thing happens with water if you place down a water bucket on an existing source. Here is the error log from crashing when picking up lava in a bucket.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.9-3.6.9.jar)
  Reborn Core ASM (RebornCore-1.9-2.0.4.46-universal.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 4/12/16 9:26 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at reborncore.common.util.BucketHandler.fillCustomBucket(BucketHandler.java:38)
	at reborncore.common.util.BucketHandler.onBucketFill(BucketHandler.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_223_BucketHandler_onBucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:297)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:39)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:159)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:483)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1538)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2171)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1743)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at reborncore.common.util.BucketHandler.fillCustomBucket(BucketHandler.java:38)
	at reborncore.common.util.BucketHandler.onBucketFill(BucketHandler.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_223_BucketHandler_onBucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:297)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:39)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:159)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:483)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1538)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2171)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)

**Comment by modmuss50** [comment] 2016-04-13 06:52
Dupe of #14, I will get aroud to fixing this asap

**Closed by modmuss50** 2016-04-13 06:52 UTC

**Comment by shortybsd** [comment] 2016-04-13 17:48
Issue is fixed with versions
RebornCore-1.9-2.0.5.50-universal and 
TechReborn-1.9-1.0.5.173-universal

Thanks man!

**Comment by modmuss50** [comment] 2016-04-13 19:33
Yeah, no worries thanks for reminding me
