### ISSUE TITLE
incompatibility issue

### ISSUE THREAD

**Issue by IchigoGames** [TechReborn/RebornCore#48] opened 2017-05-10 19:09 UTC
can you fix the compatibility of RebornCore with TickProfiler atm you have to remove RebornCore and any mods that you it for TickProfiler to work on server.

**Comment by modmuss50** [comment] 2017-05-10 19:09
Can I have a link to the TickProfiler mod? And a log if it crashes? What happens? How do i make it happen?

**Comment by IchigoGames** [comment] 2017-05-10 20:19
i know this may sound odd but the for 1.10 is the one that works on 1.11.2 https://jenkins.nallar.me/job/TickProfiler/ can you give me some time on the rest ? i got to get the logs and info from some one who is not online atm but should be back in a few hours.

**Comment by cjm721** [comment] 2017-05-10 22:07
Its because the class loader you are using enforces signing and tickprofiler uses bytecode manipulation to add in all of its hooks into classes. To reproduce all you need to do is load a server with reborn core and tickprofiler.

Mod:
https://github.com/nallar/TickProfiler

Log:
https://gist.github.com/cjm721/86399bc502d1f9f2fdc06d2e855f4bce

**Comment by modmuss50** [comment] 2017-05-10 22:07
Uhh, ok. This is going to be a fun one to fix...

**Comment by modmuss50** [comment] 2017-05-10 22:30
Ok, I think the issue is that we are both using the same library to handle asm and he is on an older version.

**Comment by modmuss50** [comment] 2017-05-14 17:48
Should be fixed their side

**Closed by modmuss50** 2017-05-14 17:48 UTC
