### ISSUE TITLE
RebornCore-1.9-2.0.2.28 crashes client on startup using forge 1.9 build 1811

### ISSUE THREAD

**Issue by kreezxil** [TechReborn/RebornCore#9] opened 2016-03-26 19:47 UTC
fml latest: http://paste.ee/p/Sl5A3

crash: http://paste.ee/p/AhKm5

**Comment by modmuss50** [comment] 2016-03-27 00:32
Dupe of #7

**Closed by modmuss50** 2016-03-27 00:32 UTC
